language: php

php:
  - 7.3

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  include:
    - stage: PHPUnit

      before_script:
      - cp .env.travis .env
      - mysql -e 'create database homas_test;'
      - composer self-update
      - travis_retry composer install --no-interaction --prefer-dist --no-suggest
      - php artisan migrate --no-interaction -vvv
      - php artisan db:seed --no-interaction -vvv

      script:
        - vendor/bin/phpunit --coverage-clover=coverage.xml
        - vendor/bin/psalm --show-info=false

      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: Dusk
      addons:
        chrome: stable

      before_script:
      - cp .env.dusk.travis .env
      - mysql -e 'create database homas_test;'
      - composer self-update
      - travis_retry composer install --no-interaction --prefer-dist --no-suggest
      - php artisan migrate --no-interaction -vvv
      - php artisan db:seed --no-interaction -vvv
      - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      - php artisan serve &

      script:
        - php artisan dusk
